import { MOCK_MEDICAL_SUMMARY } from "@/data/mockMedicalSummary";
import { MedicalSummary } from "@/types/medical";

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const SUMMARY_MODEL = process.env.OPENAI_SUMMARY_MODEL ?? "gpt-4o-mini";

const medicalSummarySchema = {
  type: "object",
  additionalProperties: false,
  required: ["patientSummary", "tasks", "medications", "followUp", "warnings"],
  properties: {
    patientSummary: { type: "string" },
    tasks: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["task", "details"],
        properties: {
          task: { type: "string" },
          details: { type: "string" }
        }
      }
    },
    medications: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "dosage", "frequency", "times", "duration", "instructions"],
        properties: {
          name: { type: "string" },
          dosage: { type: "string" },
          frequency: { type: "string" },
          times: {
            type: "array",
            items: { type: "string" }
          },
          duration: { type: "string" },
          instructions: { type: "string" }
        }
      }
    },
    followUp: {
      type: "object",
      additionalProperties: false,
      required: ["required", "date", "notes"],
      properties: {
        required: { type: "boolean" },
        date: { type: "string" },
        notes: { type: "string" }
      }
    },
    warnings: {
      type: "array",
      items: { type: "string" }
    }
  }
};

function mockSummary(transcript: string, reason: string): MedicalSummary {
  return {
    ...MOCK_MEDICAL_SUMMARY,
    sourceTranscript: transcript,
    doctorApproved: false,
    approvedAt: undefined,
    reviewNotes: [
      reason,
      "AI-generated content must be reviewed and approved before the patient can view it.",
      "Medication instructions should be checked against the original prescription."
    ]
  };
}

function extractResponseText(data: unknown) {
  const response = data as {
    output_text?: string;
    output?: Array<{
      content?: Array<{
        type?: string;
        text?: string;
      }>;
    }>;
  };

  if (response.output_text) {
    return response.output_text;
  }

  return response.output
    ?.flatMap((item) => item.content ?? [])
    .map((content) => content.text ?? "")
    .join("")
    .trim();
}

function normaliseSummary(summary: MedicalSummary, transcript: string): MedicalSummary {
  return {
    ...summary,
    patientSummary: summary.patientSummary ?? "",
    tasks: summary.tasks ?? [],
    medications: summary.medications ?? [],
    followUp: summary.followUp ?? { required: false, date: "", notes: "" },
    warnings: summary.warnings ?? [],
    sourceTranscript: transcript,
    doctorApproved: false,
    approvedAt: undefined,
    reviewNotes: [
      `Structured JSON generated by backend LLM model ${SUMMARY_MODEL}.`,
      "AI-generated content must be reviewed and approved before the patient can view it.",
      "Medication instructions should be checked against the original prescription."
    ]
  };
}

export async function generateSummaryFromTranscript(transcript: string): Promise<MedicalSummary> {
  if (!process.env.OPENAI_API_KEY) {
    await delay(1000);
    return mockSummary(transcript, "No OPENAI_API_KEY is configured, so mock summary JSON was used.");
  }

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: SUMMARY_MODEL,
      input: [
        {
          role: "system",
          content:
            "You convert doctor consultation transcripts into plain-language patient instructions. Return only structured JSON. Do not invent medication details. Use 'Needs doctor review' for missing or unclear medication fields."
        },
        {
          role: "user",
          content: transcript
        }
      ],
      text: {
        format: {
          type: "json_schema",
          name: "medical_note_summary",
          strict: true,
          schema: medicalSummarySchema
        }
      }
    })
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => "");
    throw new Error(`OpenAI summary generation failed: ${detail || response.statusText}`);
  }

  const text = extractResponseText(await response.json());

  if (!text) {
    throw new Error("OpenAI summary generation did not return JSON text.");
  }

  return normaliseSummary(JSON.parse(text) as MedicalSummary, transcript);
}

export async function mockGenerateSummaryFromTranscript(transcript: string): Promise<MedicalSummary> {
  await delay(1000);

  return mockSummary(transcript, "Mock summary JSON was requested.");
}
